### PR TITLE
V3 Major code refactoring

### PR DESCRIPTION
**Pull request by jsetton**
@digitaldan I restructured the whole project. Hopefully, it is to your liking 😄 Let me know what you think. It solves the global variable issue and I believe makes it much easier to maintain going forward.

I included your idea of getting the OH server regional settings after all. This will be useful to determine the locale settings for new capabilities such as ModeController. For now, it is just used to determine the temperature scale as you initially intended.

Fixes: #157 

**Changes**
* improved alexa capability settings and property state normalization management
* improved alexa response data validation
* moved alexa directives support into seperate classes
* added alexa property schema concept to manage property states
* updated input controller to latest api changes
* renamed thermostat setpoint comfort range parameter to use camelcase format
* removed playback support for stop operation in line with player item type command support
* added ability to use openhab regional settings to determine temperature scale
* added log error test capture preventing unecessary output during successful test units
* added alexa official json schema validation to test suite
* restructed project folders

### CODE REVIEW

**Comment by digitaldan** [comment]
Wow !  I’m just traveling back from a trip , will review on the plane .

**Comment by digitaldan** [comment]
This looks great, very much appreciate refactoring interfaces into their own classes in  ./alexa/v3/ , still working through the changes just to understand, took a little bit to wrap my head around config.js and capabilities.js .  Still poking around, but i like it :-)

**Comment by jsetton** [comment]
No worries. Thanks for the feedback. Feel free to put comment in code review if you want some clarification.

**Comment by digitaldan** [comment]
Since this is a major leap forward for maintainability I'm going to merge it and if i run into anything i will open a ticket or PR.  Awesome work.

**Pull request merged**
