### PR TITLE
Add semantic extensions support

### PR DESCRIPTION
**Pull request by jsetton**
Fixes: #283

### CODE REVIEW

**Comment by digitaldan** [comment]
Very cool!  I have some zwave/somfy blinds i will hook up to this tonight and let you know.  Code looks great, but i will take a deeper look when i play with the functionality.  Definitely a requested feature.

**Comment by jsetton** [comment]
@digitaldan Looking for some feedback on the semantic metadata parameters syntax I came up with. It looks pretty straight forward to me but wanted to hear your point of view. I kept it close to how it is defined in Alexa Skill API.

**Comment by digitaldan** [comment]
Been testing this all day yesterday, Looks great! I say merge it!

**Comment by jsetton** [comment]
Awesome! 👍 What about my other point related to the `Blind` metadata label? What are your thoughts?

**Comment by digitaldan** [comment]
>Also, the Blind metadata label currently have the Lower and Raise action semantics as +/-10% adjustment range values. I am wondering if we should just have them match the Close and Open actions. 

i think that makes sense, some blinds only have on/off, fully up or down settings anyways.  The example usage shows how to overwrite that anyways with ` actionMappings="Close=100,Open=0,Lower=(+10),Raise=(-10)"` , correct?  So the default behavior works for everyone, and advanced configs can further customize behavior. 

>Another point, I noticed that the Google Assistant integration uses tag Blinds.

I say use the correct value, so `Blind`.

**Comment by jsetton** [comment]
> i think that makes sense, some blinds only have on/off, fully up or down settings anyways. The example usage shows how to overwrite that anyways with actionMappings="Close=100,Open=0,Lower=(+10),Raise=(-10)" , correct? So the default behavior works for everyone, and advanced configs can further customize behavior.

This is correct. I will keep it as is then.

**Pull request merged**
