### PR TITLE
Remove OH1 because it doesn't work with current implementation (Homekit tags)

### PR DESCRIPTION
**Pull request by paphko**
The current implementation uses Homekit tags which does not work with OH1 because it does not support tags. And since OH2 is intended to replace OH1, I suggest to remove OH1-related code entirely.

I successfully tested [this fork](https://github.com/paphko/openhab-alexa/tree/oh1_oh2_groups) which uses a dedicated group to bind items to Alexa, but this has further drawbacks (the item name must be used  as device name, which is typically rather technical and not suited for voice recognition; the reason is that labels are also not supported in OH1 REST API). So if there is someone who wants to use this Skill for OH1, the aforementioned fork can be used.

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi Paphko, thanks for the feedback and work.  I think we should remove it as well.  I left it in there just in case someone else wanted to play with it, but as you have discovered it's difficult to support in a standard way on OH1.  Also since this is exactly the code we will be running for the official openHAB published skill, I think this project should not contain functionality we would not support there.

**Comment by digitaldan** [comment]
I am going to go ahead and merge this, thanks!

**Comment by cole701** [comment]
Does removing the OH1 support with this issue also then close out issue #4 which requests OH1 support or did I read it wrong?

**Comment by digitaldan** [comment]
I would say so, I will go ahead and close.

**Pull request merged**
