### PR TITLE
Icons for custom skill

### PR DESCRIPTION
**Pull request by 2devnull**

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi, the github URL’s for the logos, where did those come from?  Are they something you uploaded or did you find them from somewhere else?

**Comment by 2devnull** [comment]
I found it [here](https://www.openhab.org/assets/images/openhab-logo-square.png) and resized it.

**Comment by digitaldan** [comment]
Thanks, but after you resized it, where is the link we are pulling from located? I see its a github URL, but am not clear where thats actually pointed to.

**Comment by 2devnull** [comment]
It is stored on github I assume as I just dragged it into this comment box. You can do a "Save as" and host it on the openhab website if you do not want to use github to serve the files.

**Pull request closed without merging**
