### PR TITLE
Skill Manifest Environmental Variable Placeholder Support

### PR DESCRIPTION
**Pull request by jsetton**
@digitaldan I noticed that you had updated the skill instructions in a previous PR that wasn't merged. Added this in case it was missed.

### CODE REVIEW

**Comment by digitaldan** [comment]
i checked that change  in then realized that the openhab demo user's password was contained in the review instructions, so i reverted/deleted it. i thought i had pushed an update with just the removed password, but maybe i forgot to push it, or submit a PR (i'm juggling multiple projects this weekend) .  In any case, i quickly changed the demo password, so the one in this file won't actually work.  Have not given much thought to how to solve this issue.

**Comment by jsetton** [comment]
No worries. I just open this PR as a reminder. Do you want me to update it removing the password or should I just close it?

**Comment by jsetton** [comment]
> Have not given much thought to how to solve this issue.

We could use an environmental variable with the password that will get added to the skill manifest. I will update this PR with my thought.

**Comment by jsetton** [comment]
So I added support for placeholders based on environment variable. In the testing instructions case, you would use based on the example below.

```
ASK_TESTING_PASS=<password> ask deploy
```

Let me know what you think. It might be over engineered maybe 😄 The placeholder should be named the same as environment variable without `ASK_` prefix (e.g. `ASK_TESTING_PASS` => `%TESTING_PASS%`)

**Comment by digitaldan** [comment]
I like it!

**Pull request merged**
