### PR TITLE
Set skill distribution mode based on deploy environment

### PR DESCRIPTION
**Pull request by jsetton**
Only use public distribution mode for production deployment, otherwise set it as private by default.

```
ASK_ENV=production ask deploy
```

### CODE REVIEW

**Comment by jsetton** [comment]
Let me fix that one.

**Comment by digitaldan** [comment]
Sounds good, I have also granted you maintainer rights , so you can approve pull requests, write to master , etc, etc.   I hate being the bottleneck here :-)

**Comment by jsetton** [comment]
> Sounds good, I have also granted you maintainer rights , so you can approve pull requests, write to master , etc, etc. I hate being the bottleneck here :-)

Thank you very much!

> Let me fix that one.

It's fixed. I just wanted to know if you liked the idea. The thinking behind is that even though someone tries to go through the publishing process it would end up just being a private skill.

**Comment by digitaldan** [comment]
lgtm!

**Pull request merged**
