### PR TITLE
Add v2 backward compatibility

### PR DESCRIPTION
**Pull request by jsetton**
* restructured project to clearly separate v2/v3

### CODE REVIEW

**Comment by jsetton** [comment]
@digitaldan I decided to add v2 support back in the skill after reading [this documentation](https://developer.amazon.com/docs/smarthome/smart-home-skill-migration-guide.html#ensure-smooth-customer-migration) which stipulates that the skill should handle both versions until the skill no longer receive any v2 requests.

Also looking at the live skill logs, there are a ton of payload version errors still and these are for actual user requests to control their smart home devices. So rather force these users to spend the time to figure out their issue, we might as well make the experience as smooth as possible 😄

Anyway, let me know what you think. I made a minor project restructuring and added a few minor changes including having rest requests accept gzip compression if available which I think should be enabled with the myopenhab cloud connector #253.

On a side note, the state field is still being pulled in this one. I am hoping that having the request data compressed would resolve that matter.

**Comment by digitaldan** [comment]
So given the size of the PR i will have to take your word on this one :-)  I can't easily tell what code you had to change and what was pulled in from the v2 connecter.  I hope it was not as much work as it looks.

**Comment by digitaldan** [comment]
Nm my previous comment, i was not looking at the PR correctly and seeing files renamed vs added.  Changes looks good to me, super impressed at the v2 test classes you wrote, that does seem like a lot of work!   Thanks!

**Comment by jsetton** [comment]
> I hope it was not as much work as it looks.

Not too much 😄 I had to cleanup and update a bit of the v2 ohConnector to integrate in the current framework. Most of the change is from the folder restructure. I think it make sense and was needed anyway.

> super impressed at the v2 test classes you wrote, that does seem like a lot of work

That part was actually the easier one. We already had the [test cases](https://github.com/openhab/openhab-alexa/commit/09945aa158fa7325217f24165aa59b21d6ceb96c) 😄

**Comment by jsetton** [comment]
So I just pushed #265 to the live skill and will wait a day before merging and pushing this one to prod. That way we can see if the discovery performance changes improve the number of users that weren't able to have their devices converted to v3 because of the timeout issue.

**Comment by digitaldan** [comment]
👍

**Comment by digitaldan** [comment]
How did #265 go?  Do we need to push this one now?

**Comment by jsetton** [comment]
So I just opened #269 related to #265. I think we should resolve that one before merging this PR. Unless you think otherwise.

**Pull request merged**
