### PR TITLE
Large Item Collection Discovery Lambda Timeout Fix

### PR DESCRIPTION
**Pull request by jsetton**
* optimized rest items query by disabling recursive parameter
* limited rest items query output to a list of fields use by skill

Fixes: #242

### CODE REVIEW

**Comment by digitaldan** [comment]
I'll give it a try, but LGTM .  Pleasantly surprised how small the actual change was to the logic.  Nice job!

**Comment by jsetton** [comment]
I just made an improvement by moving the group member filtering part only for endpoint-enabled groups along with the conversion. Make sure to get the latest update when testing.

**Comment by digitaldan** [comment]
Something is not working with my environment which is causing discovered items to not show up.  I don't think its related at all to the changes in code but something with my setup i need to debug.  

I did however manage to run both the production skill and this version and diff'd  the response message.  The only difference in the 5334 lines of JSON was the messageId , which is of-course expected.  So I feel good this change.  I  need to turn in , but will pick this back up in the AM.  If you are comfortable with it i am good to push to production.

**Comment by jsetton** [comment]
I am happy with the change. I tested as well on my end and none of my already discovered devices went offline which is a good sign 👍 It would be good if we could get the logger config changes included as well if you are fine with them.

Let me know if you need help pushing to production. For reference, in case you didn't know, you can simply update all production lambda functions only, using the ask-cli target parameter.

```
ask deploy -t lambda
```

**Comment by digitaldan** [comment]
Sounds good, I take a look at the logger changes, but i'm sure they are fine.

> using the ask-cli target parameter.

yep, thats how i have been pushing the updates!

**Pull request merged**
