### PR TITLE
Fixes powerstate issue

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: digitaldan <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
@jsetton this seems to fix the issue over at #123 about ON/OFF not working with  dimmers.  Not sure if there are other places we need to do this.

**Comment by jsetton** [comment]
So the issue is related to the item state normalization function. It now adds the state presentation format on these items and the isNaN function isn't able to check properly with a unit. Let me take a look at it further.

**Comment by digitaldan** [comment]
Parseimt and parsefloat both read a string to the end of it or to the first non numeric character , and rerurn nan if no number is found , apparently isnan does not do this same parsing

**Comment by jsetton** [comment]
I am making a change to limit that normalization to only use the first format specifier from the description pattern since the main purpose for it was to control number precision. I don't see why we should open it to such a huge amount of possibilities as it will could bring a lot of unforeseen issues.

Another potential issue with using the full pattern that I found is that the parse functions can't get a number if there is a non numerical character at the beginning.

```
> a = ">40%<"
'>40%<'
> parseInt(a)
NaN
```

**Comment by jsetton** [comment]
I just submitted #154. Let me know if this fix works for you.

**Pull request closed without merging**
