### PR TITLE
Improve thermostat setpoints support

### PR DESCRIPTION
**Pull request by jsetton**
* added setpoint mode determination logic based on current thermostat mode
* limited requests/responses based on setpoint mode
* added thermostat mode parameter to disable setpoint mode logic if necessary
* added various thermostat setpoints condition error checks
* prevented setpoint updates if thermostat is off
* improved dual mode set/adjust logic to update one setpoint in heat/cool mode
* prevented upper/lower properties from being discovered if only one configured
* added upper/lower minimum temperature delta check based on comfort range
* increased default comfort range to 2F/1C
* decreased default setpoint minimum range to 4C/40F
* added separate dual mode eco setpoints support

Fixes: #271

### CODE REVIEW

**Comment by digitaldan** [comment]
Code looks good, I have not run it yet, was planning on doing that tonight when i'm back, not expecting any issues, but i will let you know how it goes. Thanks!

**Comment by digitaldan** [comment]
Just FYI i have been testing this on an off today.  One issue i am having is that my thermostats are not reporting their mode back in a reportState response, only the setpoints and current temperature. My item looks like this (minus the setpoints):
```
Group  F1_GreatRoom_HVAC  "Great Room Thermostat" {alexa="Thermostat"}
String F1_GreatRoom_HVAC_Mode  "Mode [%s]" (F1_GreatRoom_HVAC,HVAC_Mode) alexa="ThermostatController.thermostatMode" }
```

Possible values are `off,heat,cool,auto` for this item.  Right now it's set to `heat` (not null or something) .

I'm assuming this is actually a config error on my part, but i'm still poking around as i don't see any error or warning in the logs.

**Comment by jsetton** [comment]
There is missing open curly bracket in your mode item definition. Not sure if it's a copy paste issue or the reason for it.

**Comment by digitaldan** [comment]
Yes, it was copy and past error, here is the full definition
```
Group  F1_GreatRoom_HVAC                        "Great Room Thermostat"                                                                          {alexa="Thermostat"}
Number:Temperature F1_GreatRoom_HVAC_Temperature            "Temperature [%d °F]"      <dd_thermostat>	    (F1_GreatRoom_HVAC,HVAC_Temperatures_F1)     {channel="venstarthermostat:colorTouchThermostat:a0cc2b50e542:temperature", alexa="TemperatureSensor.temperature"  }
Number:Temperature F1_GreatRoom_HVAC_HeatSetpoint           "Heat Setpoint [%d °F]"    <dd_thermostat_heat>	(F1_GreatRoom_HVAC)		                     {channel="venstarthermostat:colorTouchThermostat:a0cc2b50e542:heatingSetpoint", alexa="ThermostatController.lowerSetpoint"  }
Number:Temperature F1_GreatRoom_HVAC_CoolSetpoint           "Cool Setpoint [%d °F]"    <dd_thermostat_cool>	(F1_GreatRoom_HVAC)		                     {channel="venstarthermostat:colorTouchThermostat:a0cc2b50e542:coolingSetpoint", alexa="ThermostatController.upperSetpoint" }
String F1_GreatRoom_HVAC_Mode                   "Mode [%s]"                 	                    (F1_GreatRoom_HVAC,HVAC_Mode)		         {channel="venstarthermostat:colorTouchThermostat:a0cc2b50e542:systemMode",  alexa="ThermostatController.thermostatMode" }
   
```

>Also, what binding channel are you using?
I removed my binding/mode mappings as i believe our docs say the default is `defaults to [OFF="off", HEAT="heat", COOL="cool", ECO="eco", AUTO="auto"] `   I can try specifically setting this.

**Comment by jsetton** [comment]
> I removed my binding/mode mappings as i believe our docs say the default is defaults to [OFF="off", HEAT="heat", COOL="cool", ECO="eco", AUTO="auto"]

That's correct. The reason I asked for the binding channel is that there are default based on binding as well but `venstarthermostat` isn't defined so it doesn't come into play.

I just tried the below item definition and no issue either. Can you see what's the output of the state report in your Lambda logs? You might need to increase log level to info.

**Item Definition**
```
Group  F1_GreatRoom_HVAC "Great Room Thermostat" {alexa="Thermostat"}
Number:Temperature F1_GreatRoom_HVAC_Temperature "Temperature [%d °F]" (F1_GreatRoom_HVAC) {alexa="TemperatureSensor.temperature"}
Number:Temperature F1_GreatRoom_HVAC_HeatSetpoint "Heat Setpoint [%d °F]" (F1_GreatRoom_HVAC) {alexa="ThermostatController.lowerSetpoint"}
Number:Temperature F1_GreatRoom_HVAC_CoolSetpoint "Cool Setpoint [%d °F]" (F1_GreatRoom_HVAC) {alexa="ThermostatController.upperSetpoint"}
String F1_GreatRoom_HVAC_Mode "Mode [%s]" (F1_GreatRoom_HVAC) {alexa="ThermostatController.thermostatMode"}
```

**Report State Property Response**
```
[
    {
        "namespace": "Alexa.TemperatureSensor",
        "name": "temperature",
        "value": {
            "value": 68,
            "scale": "FAHRENHEIT"
        },
        "timeOfSample": "2019-12-12T22:45:07.847Z",
        "uncertaintyInMilliseconds": 0
    },
    {
        "namespace": "Alexa.ThermostatController",
        "name": "thermostatMode",
        "value": "HEAT",
        "timeOfSample": "2019-12-12T22:45:07.847Z",
        "uncertaintyInMilliseconds": 0
    },
    {
        "namespace": "Alexa.ThermostatController",
        "name": "targetSetpoint",
        "value": {
            "value": 70,
            "scale": "FAHRENHEIT"
        },
        "timeOfSample": "2019-12-12T22:45:07.847Z",
        "uncertaintyInMilliseconds": 0
    },
    {
        "namespace": "Alexa.EndpointHealth",
        "name": "connectivity",
        "value": {
            "value": "OK"
        },
        "timeOfSample": "2019-12-12T22:45:07.847Z",
        "uncertaintyInMilliseconds": 0
    }
]
```

**Comment by jsetton** [comment]
I took a quick look at the `venstarthermostat` binding code on your repository. Not sure which version you are using but I believe the mode are actually numbers and depending on the binding version, the item type can be a String or Number. Unless you made additional changes 😄 

Anyway that would explain the mode not being reported issue since the default mapping wouldn't match the one from the binding.

**Comment by digitaldan** [comment]
systemMode is a string, there is also a systemModeRaw which is the numeric version.  There is a PR open with the latest branch which is not the one i have in my repo.  You can see the system mode enum here https://github.com/hww3/openhab2-addons/blob/hww3/venstar_thermostat_release/bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSystemMode.java#L21  


But this is now odd, i just checked it again, and now its reporting the mode, but not the setpoints.  Strange..... FYI there are values for the setpoints, so i don't know why i'm getting an incomplete response

```
{
    "context": {
        "properties": [
            {
                "namespace": "Alexa.ThermostatController",
                "name": "thermostatMode",
                "value": "OFF",
                "timeOfSample": "2019-12-13T04:52:26.377Z",
                "uncertaintyInMilliseconds": 0
            },
            {
                "namespace": "Alexa.TemperatureSensor",
                "name": "temperature",
                "value": {
                    "value": 74,
                    "scale": "FAHRENHEIT"
                },
                "timeOfSample": "2019-12-13T04:52:26.377Z",
                "uncertaintyInMilliseconds": 0
            },
            {
                "namespace": "Alexa.EndpointHealth",
                "name": "connectivity",
                "value": {
                    "value": "OK"
                },
                "timeOfSample": "2019-12-13T04:52:26.377Z",
                "uncertaintyInMilliseconds": 0
            }
        ]
    }
```


and here is the current state of that group from the OH rest API

```
{
    "members": [
      {
        "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC_Temperature",
        "state": "74.0 °F",
        "stateDescription": {
          "pattern": "%d °F",
          "readOnly": true,
          "options": []
        },
        "type": "Number:Temperature",
        "name": "F1_GreatRoom_HVAC_Temperature",
        "label": "Temperature",
        "category": "dd_thermostat",
        "tags": [],
        "groupNames": [
          "F1_GreatRoom_HVAC",
          "HVAC_Temperatures_F1"
        ]
      },
      {
        "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC_HeatSetpoint",
        "state": "74.0 °F",
        "stateDescription": {
          "minimum": 40,
          "maximum": 80,
          "step": 1,
          "pattern": "%d °F",
          "readOnly": false,
          "options": []
        },
        "type": "Number:Temperature",
        "name": "F1_GreatRoom_HVAC_HeatSetpoint",
        "label": "Heat Setpoint",
        "category": "dd_thermostat_heat",
        "tags": [],
        "groupNames": [
          "F1_GreatRoom_HVAC"
        ]
      },
      {
        "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC_CoolSetpoint",
        "state": "70.0 °F",
        "stateDescription": {
          "minimum": 60,
          "maximum": 95,
          "step": 1,
          "pattern": "%d °F",
          "readOnly": false,
          "options": []
        },
        "type": "Number:Temperature",
        "name": "F1_GreatRoom_HVAC_CoolSetpoint",
        "label": "Cool Setpoint",
        "category": "dd_thermostat_cool",
        "tags": [],
        "groupNames": [
          "F1_GreatRoom_HVAC"
        ]
      },
      {
        "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC_Mode",
        "state": "off",
        "stateDescription": {
          "pattern": "%s",
          "readOnly": false,
          "options": [
            {
              "value": "off",
              "label": "Off"
            },
            {
              "value": "heat",
              "label": "Heat"
            },
            {
              "value": "cool",
              "label": "Cool"
            },
            {
              "value": "auto",
              "label": "Auto"
            }
          ]
        },
        "commandDescription": {
          "commandOptions": [
            {
              "command": "off",
              "label": "Off"
            },
            {
              "command": "heat",
              "label": "Heat"
            },
            {
              "command": "cool",
              "label": "Cool"
            },
            {
              "command": "auto",
              "label": "Auto"
            }
          ]
        },
        "type": "String",
        "name": "F1_GreatRoom_HVAC_Mode",
        "label": "Mode",
        "tags": [],
        "groupNames": [
          "F1_GreatRoom_HVAC",
          "HVAC_Mode"
        ]
      },
      {
        "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC_Humidity",
        "state": "52.0",
        "stateDescription": {
          "minimum": 0,
          "maximum": 100,
          "pattern": "%d %%",
          "readOnly": true,
          "options": []
        },
        "type": "Number",
        "name": "F1_GreatRoom_HVAC_Humidity",
        "label": "Humidity",
        "tags": [],
        "groupNames": [
          "F1_GreatRoom_HVAC"
        ]
      },
      {
        "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC_State",
        "state": "idle",
        "stateDescription": {
          "pattern": "%s",
          "readOnly": true,
          "options": [
            {
              "value": "idle",
              "label": "Idle"
            },
            {
              "value": "heating",
              "label": "Heating"
            },
            {
              "value": "cooling",
              "label": "Cooling"
            },
            {
              "value": "lockout",
              "label": "Lockout"
            },
            {
              "value": "error",
              "label": "Error"
            }
          ]
        },
        "commandDescription": {
          "commandOptions": [
            {
              "command": "idle",
              "label": "Idle"
            },
            {
              "command": "heating",
              "label": "Heating"
            },
            {
              "command": "cooling",
              "label": "Cooling"
            },
            {
              "command": "lockout",
              "label": "Lockout"
            },
            {
              "command": "error",
              "label": "Error"
            }
          ]
        },
        "type": "String",
        "name": "F1_GreatRoom_HVAC_State",
        "label": "State",
        "tags": [],
        "groupNames": [
          "F1_GreatRoom_HVAC"
        ]
      }
    ],
    "link": "http://oh:8080/rest/items/F1_GreatRoom_HVAC",
    "state": "NULL",
    "editable": false,
    "type": "Group",
    "name": "F1_GreatRoom_HVAC",
    "label": "Great Room Thermostat",
    "tags": [],
    "groupNames": []
  }
```

**Comment by jsetton** [comment]
So this is normal when the thermostat is OFF. Only the mode is sent back since setpoints are not relevant. It's described in the usage documentation. Alexa would just respond "Thermostat is off"

**Comment by digitaldan** [comment]
> Only the mode is sent back since setpoints are not relevant. It's described in the usage documentation.

I did not realize that.  I was looking through the API docs and I don't see anywhere that says to limit the state reporting based on the current mode, maybe i missed that? Does sending all of the values not give an accurate response when asked?   If the state report is triggered by the web/mobie/show UI then I would think it would want all the info to show in its graphic.  Right now i get an error message on my echo show when trying to display thermostats from the smart home menu,, although asking about its mode will report back the correct value . The mobile UIs work fine however, strange.

I'm not sure if this is actually a problem, or just the echo show's UI being buggy, i just got the show yesterday and am not super impressed so far.  I probably need to mess with it more. 

I'll keep looking at it today.

**Comment by digitaldan** [comment]
FYI as a test i changed the state reporting to always return back all known setpoints regardless of mode, and the Mobile UI did change to reflect this and allows me to change those values regardless of mode.  This matches my expectation on how a thermostat should work, although I realize i am probably not remembering a conversation we had about this and why its implemented this way :-)

**Comment by jsetton** [comment]
> I did not realize that. I was looking through the API docs and I don't see anywhere that says to limit the state reporting based on the current mode, maybe i missed that? Does sending all of the values not give an accurate response when asked?

That's not part of the API as per say. I added that logic in this change based on 3 things: (1) If you request with the current live skill to either change setpoints or the current status, Alexa will always respond, the thermostat is off based on the mode state part of the report; therefore discarding the setpoints values. (2) Similarly, the Alexa app will only show the thermostat mode when it's off (3) Using the logic introduced in this change, what would be the setpoints we should report since the mode is off? Likewise, if we request a target temperature when the thermostat is off, which setpoint(s) should be updated on the OH side?

The idea with this change is to only report/update setpoints when these are relevant to the mode it is currently set to. Based on all my testing, I haven't seen any issue so far.

> Right now i get an error message on my echo show when trying to display thermostats from the smart home menu,, although asking about its mode will report back the correct value .

That's interesting. I don't have an Echo device with a display yet and the Alexa simulator doesn't seem to support them for Alexa Smart Home skill yet. Any change you could attach a photo?

> i just got the show yesterday and am not super impressed so far. 

Congrats! 😄 I have been reluctant in getting one of these just for the simple fact of the amount of table footprint it would take along with cost compared to the actual need. I am actually considering moving to Echo Flex devices since I use most of my current devices connected to bluetooth speakers.

**Comment by jsetton** [comment]
> although I realize i am probably not remembering a conversation we had about this and why its implemented this way :-)

You should check #271 for our initial discussion 😄

**Comment by digitaldan** [comment]
So now its even more strange here is , a screen shot of the Mobile UI

IMG_0269

And here is the same device on the echo show, notice how the show has the heat/cool values reversed!

IMG_0272 1

**Comment by jsetton** [comment]
Are you using the changes in this PR? You shouldn't see a dual setpoints when in heat mode. Here is what I see on my end in the Alexa app using the same configuration you have on your end.

Screenshot_20191213-111921_Amazon Alexa

**Comment by digitaldan** [comment]
I mentioned above ^^
>FYI as a test i changed the state reporting to always return back all known setpoints regardless of mode,

I was curious what would be the behavior of reporting the current state of the thermo regardless of mode, which had interesting results between the two devices.  Personally I would prefer being able to have full control of setpoints regardless of mode since the UI's are designed to work that way (well, should work, the show has some issues!). Before the show, i guess it didn't matter as much since i did not use the mobile app to control stuff, but now i'm not so sure (it brings up that UI any time you voice control the thermo) .

I guess I am mixing concerns between this PR and #271 , so i'll revert the change back and just focus on testing the functionality here.

**Comment by jsetton** [comment]
Not sure if you saw on my previous response that I had edited, there is a parameter to disable that automation part of this change that you can add to the thermostat mode item `supportsSetpointMode=false` to go back to all setpoints reported at all times. Although, it's enabled by default.

While you might not see an issue with your setup since you only have two setpoints, it's different with mine using a Nest thermostat which have 5 setpoints which aren't all used at the same time.

Out of curiosity, what does your thermostat display show when it's either in heat or cool mode? Do you actually change your cooling setpoint in heat mode and vice versa?

**Comment by digitaldan** [comment]
>Out of curiosity, what does your thermostat display show when it's either in heat or cool mode? Do you actually change your cooling setpoint in heat mode and vice versa?

Thats a good question, i had to try it out as i did not remember, it will only allow setting the cooling, heating or comfort range value (4 degree difference) depending on the mode you are in.  

So far everything looks good, i could not repeat the missing mode value , so I'm going to blame that on some config issue on my part, might have been a bad cached value from an old discovery and the item type changed at some point (int to string or something) .  So i'm good with merging, I'll move on to the semantic support PR now.

>Not sure if you saw on my previous response that I had edited, there is a parameter to disable that automation part of this change that you can add to the thermostat mode item supportsSetpointMode=false to go back to all setpoints reported at all times. Although, it's enabled by default.

I missed that!

**Comment by jsetton** [comment]
> Thats a good question, i had to try it out as i did not remember, it will only allow setting the cooling, heating or comfort range value (4 degree difference) depending on the mode you are in.

So setting the cooling setpoint in cool mode, the heating setpoint in heat mode and comfort range in auto mode? That's what I would expect. It sounds like you got used to do comfort range when your thermostat is in cool or heat mode. Maybe you should leave it in auto mode 😄 

> So i'm good with merging, I'll move on to the semantic support PR now.

Awesome 👍  Are you fine with the small documentation change I made related to the eco upper/lower distinct setpoints setup based on your feedback?

By the way, going over what you mentioned above, you would actually have to define your thermostat supported modes mapping since it doesn't support eco mode. The other option would be to add the default mapping for the `venstarthermostat` binding in the skill v3 config.

**Comment by digitaldan** [comment]
I'm good that way its documented, so i say merge as is, thanks!

**Pull request merged**
