### PR TITLE
V3 logging fixes

### PR DESCRIPTION
**Pull request by digitaldan**
@jsetton  logging was not printing the second argument in the log function for me,  i ran across this bug https://github.com/winstonjs/winston/issues/1217  on the winston repo that maybe explains why, can you confirm my changes work for you before i merge?

### CODE REVIEW

**Comment by jsetton** [comment]
I am looking into this right now. FYI, I have another big code refactor improvement PR coming your way, in a bit, around Alexa capability settings and property state management. I think you will like it. 😄

**Comment by digitaldan** [comment]
👍 Awesome, I'm going to open a Bug on something I have a question on , look for it in just a min.

**Comment by jsetton** [comment]
Change looks good. Another option would have been to reintroduce the concatenation of the JSON stringify output to the log message string.

**Comment by digitaldan** [comment]
I'll merge, i kinda like the simplify of it.

**Comment by jsetton** [comment]
So I found another issue with the logger while doing some test. When the provided object includes a `message` property, it uses that property as the message. I am going to rename these properties to `reason` instead. I also confirmed that it is only when that property is at the root level. So none of the Alexa response object should be affected.

Before
`error: getPropertiesResponseAndReturn failed with error: {"message":"Invalid item state returned by openHAB","items":[{"name":"switch1","state":"NULL","type":"Switch"}]}`

Now
`error: Invalid item state returned by openHAB {"items":[{"name":"switch1","state":"NULL","type":"Switch"}]}`

**Pull request merged**
